-- StudyBuddy 模块测试数据库表结构

-- 科目表
CREATE TABLE IF NOT EXISTS "study_subject" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '主键ID',
    "user_id" bigint NOT NULL COMMENT '用户ID',
    "name" varchar(255) NOT NULL COMMENT '科目名称',
    "code" varchar(50) COMMENT '科目代码',
    "description" text COMMENT '科目描述',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '科目表';

-- 试卷表
CREATE TABLE IF NOT EXISTS "study_paper" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '主键ID',
    "paper_no" varchar(50) NOT NULL COMMENT '试卷编号',
    "student_id" bigint COMMENT '学生ID',
    "subject_id" bigint COMMENT '科目ID',
    "subject" varchar(255) COMMENT '科目名称',
    "title" varchar(255) NOT NULL COMMENT '试卷标题',
    "description" text COMMENT '试卷描述',
    "exam_date" date COMMENT '考试日期',
    "grade" varchar(50) COMMENT '年级',
    "semester" varchar(50) COMMENT '学期',
    "file_path" varchar(500) COMMENT '试卷文件存储路径',
    "status" varchar(50) DEFAULT 'UPLOADED' COMMENT '处理状态',
    "error_msg" text COMMENT '错误信息',
    "ocr_model" varchar(50) COMMENT 'OCR模型',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '试卷表';

-- 题目表
CREATE TABLE IF NOT EXISTS "study_question" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '主键ID',
    "paper_id" bigint NOT NULL COMMENT '试卷ID',
    "question_no" varchar(50) COMMENT '题目编号',
    "content" text COMMENT '题目内容',
    "knowledge_point" varchar(255) COMMENT '知识点',
    "position_json" text COMMENT '位置信息JSON',
    "standard_answer" text COMMENT '标准答案',
    "standard_answer_verified" bit DEFAULT FALSE COMMENT '标准答案是否已确认',
    "original_answer" text COMMENT '原始答案',
    "solution_approach" text COMMENT '解题思路',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '题目表';

-- 试卷文件表
CREATE TABLE IF NOT EXISTS "study_paper_file" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '主键ID',
    "paper_id" bigint NOT NULL COMMENT '试卷ID',
    "file_path" varchar(500) NOT NULL COMMENT '文件路径',
    "file_name" varchar(255) COMMENT '文件名',
    "file_type" varchar(50) COMMENT '文件类型',
    "file_size" bigint COMMENT '文件大小',
    "sort_order" int DEFAULT 0 COMMENT '排序序号',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '试卷文件表';

-- 学生答案表
CREATE TABLE IF NOT EXISTS "study_question_student_answer" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '主键ID',
    "question_id" bigint NOT NULL COMMENT '题目ID',
    "raw_answer" text COMMENT '学生原始答案',
    "is_correct" bit COMMENT '是否正确',
    "error_analysis" text COMMENT '错误分析',
    "better_solution" text COMMENT '更优解法',
    "source" varchar(50) COMMENT '答案来源',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '学生答案表';

-- 错题本表
CREATE TABLE IF NOT EXISTS "study_wrong_book" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '主键ID',
    "user_id" bigint NOT NULL COMMENT '用户ID',
    "question_id" bigint NOT NULL COMMENT '题目ID',
    "paper_id" bigint COMMENT '试卷ID',
    "question_no" varchar(50) COMMENT '题号',
    "question_content" text COMMENT '题目内容',
    "knowledge_point" varchar(255) COMMENT '知识点',
    "student_answer" text COMMENT '学生答案',
    "standard_answer" text COMMENT '标准答案',
    "error_analysis" text COMMENT '错误分析',
    "better_solution" text COMMENT '更优解法',
    "wrong_count" int DEFAULT 1 COMMENT '错误次数',
    "last_wrong_time" timestamp COMMENT '最后错误时间',
    "is_mastered" bit DEFAULT FALSE COMMENT '是否已掌握',
    "mastered_time" timestamp COMMENT '掌握时间',
    "remark" varchar(500) COMMENT '备注',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '错题本表';

-- 学习统计表
CREATE TABLE IF NOT EXISTS "study_learning_stats" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '主键ID',
    "user_id" bigint NOT NULL COMMENT '用户ID',
    "knowledge_point" varchar(255) NOT NULL COMMENT '知识点',
    "total_count" int DEFAULT 0 COMMENT '总练习次数',
    "correct_count" int DEFAULT 0 COMMENT '正确次数',
    "wrong_count" int DEFAULT 0 COMMENT '错误次数',
    "accuracy_rate" decimal(15,2) COMMENT '正确率',
    "mastery_level" varchar(50) COMMENT '掌握程度',
    "last_practice_time" timestamp COMMENT '最后练习时间',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '学习统计表';

-- 访问日志表
CREATE TABLE IF NOT EXISTS "study_access_log" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '主键ID',
    "user_id" bigint COMMENT '用户ID',
    "username" varchar(100) COMMENT '用户名',
    "module" varchar(50) COMMENT '模块',
    "operation" varchar(100) COMMENT '操作',
    "request_url" varchar(500) COMMENT '请求URL',
    "request_method" varchar(10) COMMENT '请求方法',
    "request_params" text COMMENT '请求参数',
    "response_code" int COMMENT '响应码',
    "response_time" int COMMENT '响应时间（毫秒）',
    "ip" varchar(50) COMMENT 'IP地址',
    "user_agent" varchar(500) COMMENT 'User Agent',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '访问日志表';